apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  database: mongodb
  database_uri: mongodb://localhost:27017

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-env
spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
        - configMapRef:
            name: my-cm
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
