Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname= "control-node"
  config.vm.network "private_network", ip: "192.168.56.155"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
  config.vm.provision "shell", path: "provision.sh"
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
end
#sudo apt-get install nfs-common nfs-kernel-server