apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    name: web-app
spec:
  containers:
    - name: web-server-apache
      image: httpd
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
    - name: web-server-tomcat
      image: tomcat
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
