apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    type: api
  loadBalancerIP: 10.0.0.60
  ports:
    - name: http
      protocol: TCP
      port: 9001
