Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname= "db01"
  config.vm.network "private_network", ip: "192.168.56.157"
  config.vm.provision "shell", path: "provision.sh"
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
end
